### ISSUE TITLE
Referencing a specific item

### ISSUE THREAD

**Issue by AsenCME** [vuejs/vuefire#113]
Right now if I want to have a dynamic array of items that I render somewhere on my page I have to say for example:
```
firebase:{
    cart: cartRef
}
```
Now in my project I have a node with users and for every user I assign them a cart with all their items. But I don't know how to access it. I'm trying to reference it like this:
```
Firebase.auth().onAuthStateChanged(user => {
     var cartRef =  app.database().ref('users/' + user.uid + '/cart');
});
```
It is exactly this asynchronous call for the user that drives me crazy and I can't load the list properly. How should I go about retrieving this?

**Comment by posva** [comment]
Well, it depends on how you structured your database...
But I think you're looking for the `child()` function instead of `ref()` (look at the example folder)

If you need more help, I recommend you to use the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
