### ISSUE TITLE
Configure admin service account from environment variable

### ISSUE THREAD

**Issue by SamGeens** [vuejs/vuefire#1297]
### What problem is this solving

Currently the environment variable needs to be configured be adding the file name of the service account. This obligates the developer to store those secret credentials in code. Being able to configure the admin setting from string (or environment variable) would solve this.

### Proposed solution

Allow the following configuration:

`
      admin: {
        serviceAccount: JSON.parse(process.env.FIREBASE_SERVICE_ACCOUNT),
      },
`

### Describe alternatives you've considered

Adding the admin module directly within the Firebase configuration

**Comment by posva** [comment]
Right now it allows for a path to the credential files. It would be nice to support both thought

**Comment by AKodkod** [comment]
Based on type annotations you can specify `serviceAccount` as an object.

<img width="1504" alt="CleanShot 2023-02-12 at 00 00 41@2x" src="https://user-images.githubusercontent.com/678665/218293901-a35f21b0-67c1-4cb0-9ccf-8a567b493e6a.png">
<img width="462" alt="CleanShot 2023-02-12 at 00 01 30@2x" src="https://user-images.githubusercontent.com/678665/218293913-2bde5453-bcda-47bc-ae74-265e1fe336c3.png">

**Comment by chrisspiegl** [comment]
Based on the code, the environment variable method is already supported: https://github.com/vuejs/vuefire/search?q=GOOGLE_APPLICATION_CREDENTIALS

This way you just specify the env variable `GOOGLE_APPLICATION_CREDENTIALS` to be the path to your credentials and you're good to go.

I am still in the process of testing if the `GOOGLE_APPLICATION_CREDENTIALS` env variable is set on Firebase or not, but if it is, that'd be pretty nice way of doing this.

**Comment by dosstx** [comment]
Thanks that is good to know, @chrisspiegl . I'll also check on that.

**Comment by tux2nicolae** [comment]
I encounter the same problem, I'm deploying my web app in AWS ECS and it's not that easy to also deploy the `firebase.json` file inside the container during our build setup, is there a way to provide the configuration as an environment variable?

**Comment by chrisspiegl** [comment]
@tux2nicolae You can always put stuff into Environment variables and then use those at build time via `process.env.FIREBASE_{…}`. Alternatively you can also put the firebase.json files into the repo since they are deployed client side anyways — from my understanding. Just the `Google Service Account`… that's something that should never end up in a repo and should always be put into environment variables.

**Comment by tux2nicolae** [comment]
@chrisspiegl thank you for your fast replay, really appreciate it

Unfortunately I can't put the file in repo for security concerns, we are using the nuxt module so we expect that this file won't reach the client side.

Regarding the environment variables could you elaborate please? I've tried to set FIREBASE_CONFIG with the json data, but the deployment would fail because it expects the configuration file to be present on disk.

Please advise me if I'm missing anything, thx

**Comment by chrisspiegl** [comment]
@tux2nicolae I am using Nuxt as well. And I am doing it as follows:

```js
vuefire: {
    config: JSON.parse(process.env.FIREBASE_CONFIG)
}
```

And set the `FIREBASE_CONFIG` with the whole sdkConfig JSON String.

Alternatively you can also do:

```js
vuefire: {
    config: {
      projectId: process.env.FIREBASE_PROJECT_ID,
      appId: process.env.FIREBASE_APP_ID,
      apiKey: process.env.FIREBASE_API_KEY,
      messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID,
    }

JSON.parse(process.env.FIREBASE_CONFIG)
}
```

And set the values in the ENV individually.

**Comment by tux2nicolae** [comment]
@chrisspiegl thank you, indeed this solves the problem with firebase config, but I think the problem remains with the `Google Service Account` which apparently can't be provided via environment variables, did you manage to set google service account as well?

**Comment by chrisspiegl** [comment]
@tux2nicolae At this time, I was only able to provide a path to the `Google Services Account` via `GOOGLE_APPLICATION_CREDENTIALS = ./.firebase-service-account.json`… So, the credentials are still stored in a file.

For me, it doesn't matter because I am running the cloud functions on firebase functions 🙈. But, you mentioned, that you are on AWS so that's a bit of a different situation. 

I did some quick researching and found that you can setup some IAM auth service thing and that should do the trick for you — while staying secure and not having to store keys in your code: 

https://dwdraju.medium.com/calling-google-cloud-services-from-aws-using-iam-roles-without-gcp-service-account-credentials-af918c05384d

**Comment by tux2nicolae** [comment]
Thank you again for your research, very valuable information, I'll give it a try, thank you!

**Comment by robokozo** [comment]
I'm experiencing the same situation where I need to provide the `vuefire.admin.serviceAccount` but it fails on deployment because the file isn't deployed with the rest of the app. Not sure how to move forward. 

I tried filling out the info that @akodkod pointed out but not having luck with this approach either.
![image](https://user-images.githubusercontent.com/1719221/223308392-999a80ca-18e6-4e63-af2b-4dc76eb2ca96.png)

Is there a way to have nuxt copy the file when it does a build (but not expose it publicly)?

**Comment by chrisspiegl** [comment]
**I was able to get the Service Account into ENV variables.**

It's actually already possible based on ENV variables based on the below code. But there is a small quirk which needs to be set so it works. May be something to update the docs about.

The way it works is of based on these lines:

https://github.com/vuejs/vuefire/blob/83f4e099184ba5c474e013e2914bd303e01fd339/packages/nuxt/src/runtime/admin/plugin.server.ts#L23-L33

**The setup works as follows:**

- The script expects that the `GOOGLE_APPLICATION_CREDENTIALS` must be present. Not sure why because it is not the only way to set the service account and it can actually be anything. It just can not be undefiend.
- When you do not provide `GOOGLE_APPLICATION_CREDENTIALS` it gives the error:
```
[nuxt-vuefire]: You activated both SSR and auth but you are not providing an admin config. If you render or prerender any page using auth, you will get an error. In that case, provide an admin config to the nuxt-vuefire module.
```
- You can however, provide the service account via three additional ENV variables `FIREBASE_PROJECT_ID`, `FIREBASE_CLIENT_EMAIL`, and `FIREBASE_PRIVATE_KEY`
- I was able to test this and it worked.
- When setting the `GOOGLE_APPLICATION_CREDENTIALS=TEST` and the other three to their respective values, I got the following log message — and most importantly: SSR did work perfectly.
```
[nuxt-vuefire]: using FIREBASE_PRIVATE_KEY env variable
```

There are another two variables (`FIREBASE_CONFIG` and `FUNCTION_NAME`). As far as I understand, these are used when deploying directly to Google Firebase Functions and should not necessarily be used by us manually. ([Docs](https://firebase.google.com/docs/functions/config-env))

**Your .ENV config file needs to include:**

```dotenv
# VUEFIRE Firebase Authentication Service Account (path if using it, something random if you want to use the below config cause it needs to be defined even if you don't use it).
GOOGLE_APPLICATION_CREDENTIALS = "TEST"

# These can be set by the user on other platforms
FIREBASE_PROJECT_ID = your-project-id
FIREBASE_CLIENT_EMAIL = firebase-adminsdk-xxxxxx@your-project-id.iam.gserviceaccount.com
FIREBASE_PRIVATE_KEY = "-----BEGIN PRIVATE KEY-----XXXXXXXXXXXXX-----END PRIVATE KEY-----\n"
```

**Comment by robokozo** [comment]
@chrisspiegl great! i'll test it out later tonight and let you know how it goes!

**Comment by noook** [comment]
That's what I did but it seems that the session cannot be persisted for some reason server-side. Everytime I reload the page, it goes through my server middleware and the session doesn't exist

Can you confirm if you authenticate the session is maintained ?

**Comment by chrisspiegl** [comment]
@noook at this time I have not tested it with some other provider like Vercel since I am actually using Google Firebase for deploy at the moment. But I might be able to test that in the future… but pretty time strapped at the moment so that may take a while.

**Comment by noook** [comment]
Oh I can reproduce locally, but only with production build `npm run build && npm run preview`

**Comment by robokozo** [comment]
I was able to test the deploy and it worked with the info @chrisspiegl provided. 

However, once I logged in using google auth and refreshed, the app would not work anymore. I think It must be having problems SSRing my logged in user information

I would share a link for you all to see for yourselves but I noticed that the private key was copied into one of the build folders in `.output\public\_nuxt` and it makes me a little nervous posting it publicly. 

First load working:
![image](https://user-images.githubusercontent.com/1719221/224527825-76a0c63a-b88c-4b1e-b5a1-9e283801c9bf.png)

Refresh failing:
![image](https://user-images.githubusercontent.com/1719221/224527841-30a97c20-ba6b-46f9-a390-a046e8b587e6.png)

**Comment by chrisspiegl** [comment]
At least that's progress (of sorts) 🙈. 

One question: did you try loading the window in an incognito window or in a regular browser window?

Because I just recently had this strange issue #1312 where the SSR login persists across reloads in a regular browser window but in an Incognito window it is forgotten every time I reload the window which is not how I experience this type of thing on other websites.

About the PK being in the public dir, pretty sure that shouldn't be there… but nothing I have ever looked into since I am deploying to Firebase and they provide those service accounts out of the box.

**Comment by robokozo** [comment]
So my original attempts were all done in a normal chrome tab. 

But I just tried incognito and in firefox and I got even more surprising results... I couldn't log in at all. It would fail!
Firefox did log this in the console though: 

![image](https://user-images.githubusercontent.com/1719221/224556339-cc590ebc-c6e8-4686-9f02-f1c5fd6db7f8.png)

My deployment wth 100% in the firebase stack (using the firebase preset from the nitro docs)

and here is the code.

app.vue
```
<script lang="ts" setup>
import { signInWithRedirect, GoogleAuthProvider, signOut } from "firebase/auth"
const auth = useFirebaseAuth()
const user = useCurrentUser()

const login = () => {
    if (auth) {
        signInWithRedirect(auth, new GoogleAuthProvider())
    }
}

const logout = () => {
    if (auth) {
        signOut(auth)
    }
}
</script>

<template>
    <div>
        <div>hello</div>
        <button v-if="user == null" @click="login">Login</button>
        <button v-else @click="logout">Logout</button>
        <code>{{ user }}</code>
    </div>
</template>
```

nuxt.config.ts
```
export default defineNuxtConfig({
    nitro: {
        preset: "firebase",
    },
    modules: ["nuxt-vuefire"],
    vuefire: {
        auth: true,
        admin: {
            serviceAccount: {
                privateKey: process.env.FIREBASE_PRIVATE_KEY,
                clientEmail: process.env.FIREBASE_CLIENT_EMAIL,
                projectId: process.env.FIREBASE_PROJECT_ID,
            },
        },
        config: {
            apiKey: "-,
            authDomain: "-",
            projectId: "-",
            storageBucket: "-",
            messagingSenderId: "-",
            appId: "-",
        },
    },
})
```

firebase.json
```
{
    "functions": { "source": ".output/server" },
    "hosting": [
        {
            "site": "-",
            "public": ".output/public",
            "cleanUrls": true,
            "rewrites": [{ "source": "**", "function": "server" }]
        }
    ]
}

```

**Comment by noook** [comment]
I'm trying to contribute on this one, and as far as I advanced, the main issue lies in this block of code:

https://github.com/vuejs/vuefire/blob/83f4e099184ba5c474e013e2914bd303e01fd339/packages/nuxt/src/module.ts#L107-L135

The `hasServiceAccount` variable is set to `true` only when the service account admin proprerty is a path to a file (a string). Otherwise, if you provide it as an object the variable is false, and it will not register the api handler, nor the cookie mint plugin, and I believe this is where the issue is. I'm working on a PR to enable that

**Comment by robokozo** [comment]
Sounds good! @posva mentioned on his latest livestream that he is going on a (much deserved) long holiday. For now, I'm just deploying a SPA to firebase.

**Comment by robokozo** [comment]
@noook I took a look at your changes. Correct me if I'm wrong but that change will only solve the issue that @chrisspiegl mentioned where you have to set
```
GOOGLE_APPLICATION_CREDENTIALS=TEST
```
in the .env file

**Comment by chrisspiegl** [comment]
Hello everyone, I now tried to really setup a repo and test Vercel and Firebase deploy with SSR and the Google Service Account.

The repo can be found here: https://github.com/chrisspiegl/test-nuxt-vuefire-ssr

There is a whole bunch of things.

1. A way to set the **Service Account via Environment Variables** without the need of putting them into a file or anything (and no need to change the code of VueFire, although there are some things that could be improved).
2. A way to set the Front End API Key and such in the Environment Variables so that they are set at build time.
3. Both of these need to be handled differently on Vercel and Firebase but kind of the same (check the Readme on the repo).
4. **Regarding the Firebox Cookie Issue:** I found that `signInWithRedirect` does not really work well with non Firebase hosted sites because of the cookie policies. There are some instructions in the [Firebase Docs](https://firebase.google.com/docs/auth/web/redirect-best-practices) about how to work with that but I have not been able to get the `reverse proxy` method to work on Vercel. The workaroudn would be to start out using `signInWithPopup` since that works more universally. 

A disclaimer: I am not a security researcher and can't guarantee that the Private Key or anything else shows up in frontend code. Though, at this time I could not find any trace of it in my code.

I hope this helps some people get their site SSR ready on Vercel (and other environemnts). And maybe, we can improve upon these findings together and somehow work into the docs.

**Comment by noook** [comment]
@robokozo the environment variable is set [at this place](https://github.com/vuejs/vuefire/blob/main/packages/nuxt/src/module.ts#L107-L110) by reading the service account option if this one is a file. In my changes I still keep this condition and first check if I the file's path is provided, then in a second part I then check if the object is configured

**Comment by tux2nicolae** [comment]
@chrisspiegl Thank you!!! We finally managed to deploy our app using SSR thanks to you, we still need to make some more tests to make sure all is working properly, but at first look it seems to be alright

**Comment by robokozo** [comment]
@chrisspiegl It worked on vercel! I'm guessing native firebase ssr isn't quite ready yet. 

But the service account key is deployed in the client bundle :( 

![image](https://user-images.githubusercontent.com/1719221/225488538-8f99ccb7-e8fb-41f0-8e59-a05bda85b14a.png)

**Comment by chrisspiegl** [comment]
Do you have the `serviceAccount` bound to ENV variables in the `nuxt.config.js` file?
If so, you don't need to do that since those are going to be picked up by the functions from the vercel/firebase env variables.

> I'm guessing native firebase function ssr isn't quite ready yet.

Not sure what you mean by that? I have SSR working on Firebase functions?

**Comment by robokozo** [comment]
@chrisspiegl 
Yes, all done with environment variables. Check your deployment too
```
export default defineNuxtConfig({
    modules: ["nuxt-vuefire"],
    vuefire: {
        auth: true,
        admin: {
            serviceAccount: {
                privateKey: process.env.FIREBASE_PRIVATE_KEY,
                clientEmail: process.env.FIREBASE_CLIENT_EMAIL,
                projectId: process.env.FIREBASE_PROJECT_ID,
            },
        },
        config: {
            apiKey: process.env.FIREBASE_API_KEY,
            authDomain: process.env.FIREBASE_AUTH_DOMAIN,
            projectId: process.env.FIREBASE_PROJECT_ID,
            storageBucket: process.env.FIREBASE_STORAGE_BUCKET,
            messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID,
            appId: process.env.FIREBASE_APP_ID,
        },
    },
})
```

**Comment by robokozo** [comment]
@chrisspiegl 
>Not sure what you mean by that? I have SSR working on Firebase functions?

Do you, really? I've only seen you comment on deploying to vercel.
This is what happens when I deploy using the nitro `firebase` preset using `firebase deploy`. https://github.com/vuejs/vuefire/issues/1297#issuecomment-1465102607
It deploys correctly to a GCP cloud function, but the auth service account stuff doesnt seem to work

**Comment by chrisspiegl** [comment]
> @chrisspiegl Yes, all done with environment variables. Check your deployment too…

@robokozo I'll respond to both things, starting with your first comment about your `nuxt.config.ts` file.

**nuxt.config.ts**

As you can see in [my demo repo about how I managed to get it to work](https://github.com/chrisspiegl/test-nuxt-vuefire-ssr/blob/c8e13a6c819d5ddc832077d8b8fe5ef4b135dc56/nuxt.config.ts#L14-L27), you do not need the admin account setup in the `nuxt.config.ts` file at all since those `.env` variables are actually used right inside the code from `vuefire` without the need to provide them inside the `nuxt.config.ts`. So your config should look like this:

```js
export default defineNuxtConfig({
    modules: ["nuxt-vuefire"],
    vuefire: {
        auth: true,
        config: {
            apiKey: process.env.FIREBASE_API_KEY,
            authDomain: process.env.FIREBASE_AUTH_DOMAIN,
            projectId: process.env.FIREBASE_PROJECT_ID,
            storageBucket: process.env.FIREBASE_STORAGE_BUCKET,
            messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID,
            appId: process.env.FIREBASE_APP_ID,
        },
    },
})
```

By doing so, you should not see these API keys / the PRIVATE_KEY in the public js files.

**Deploy on Google Firebase:**

Yes, I deployed my test repo to both Firebase and Vercel (see [readme.md](https://github.com/chrisspiegl/test-nuxt-vuefire-ssr#firebase) on my test repo). Both worked and I was able to login and reload the page.

Also, with no real "special settings or setup". Aka: both used the same `nuxt.config.ts` setup and the only real difference is how the `.env` is deployed. Since the GCP Service Account will be provided by default in Google Firebase Functions, you do not need to provide those for the deploy at all.

Have a look into the `package.json` on my test repo to see how the build & deploy process for firebase worked for me.

**Comment by chrisspiegl** [comment]
That's incredible.

Now, we might have to update the docs to include all this information. But I would like to hear from someone of the package creators / main contributors if this is something to do or not.

**Comment by matifanger** [comment]
Hey @chrisspiegl, I'm getting this error, maybe you can help me 🙏 

![Code_DCP5EbflDO](https://user-images.githubusercontent.com/39188240/228091542-39b11c15-e50c-4f41-99d1-a008fd0ca58e.png)

This is my .env file
![c0AbuMkTSl](https://user-images.githubusercontent.com/39188240/228091771-2d715faf-59de-4ebe-9fad-36bcbd1a2598.png)


And my nuxt.config.ts
![Code_IckH7I0A3R](https://user-images.githubusercontent.com/39188240/228091582-fb06a619-b642-48b7-84ab-0d41e3b10e3f.png)

**Comment by matifanger** [comment]
> Hey @chrisspiegl, I'm getting this error, maybe you can help me 🙏
> 
> ![Code_DCP5EbflDO](https://user-images.githubusercontent.com/39188240/228091542-39b11c15-e50c-4f41-99d1-a008fd0ca58e.png)
> 
> This is my .env file ![c0AbuMkTSl](https://user-images.githubusercontent.com/39188240/228091771-2d715faf-59de-4ebe-9fad-36bcbd1a2598.png)
> 
> And my nuxt.config.ts ![Code_IckH7I0A3R](https://user-images.githubusercontent.com/39188240/228091582-fb06a619-b642-48b7-84ab-0d41e3b10e3f.png)

Forget it, it's working. I just changed the way that I was using my ENV `FIREBASE_CONFIG`. I created every key separated like your example, and now it's working, at least in local. I will check it out in Netlify now.

**Comment by posva** [comment]
> @chrisspiegl It worked on vercel! (Both redirect and popup) I'm guessing native firebase function ssr isn't quite ready yet.
> 
> But the service account key is deployed in the client bundle :(
> 
> ![image](https://user-images.githubusercontent.com/1719221/225488538-8f99ccb7-e8fb-41f0-8e59-a05bda85b14a.png)

Yeah, I think using the env variable containing the filepath or the JSON object is better to avoid this security issue... BTW I imagine you know but you should probably revoke that key and delete it in your Firebase console.

This should be fixed in 693af39, it needs to be released and documented but the idea is to use `GOOGLE_APPLICATION_CREDENTIALS` env variable. It will be parsed as an object if the first character is `{` and allows deploying even outside of Firebase (Vercel, Netlify)

**Comment by polymer-coder** [comment]
> serviceAccount: {
>                 privateKey: process.env.FIREBASE_PRIVATE_KEY,
>                 clientEmail: process.env.FIREBASE_CLIENT_EMAIL,
>                 projectId: process.env.FIREBASE_PROJECT_ID,
>             },

This solved my issue but if you're still facing issues, after two days of trying, just delete your  `.nuxt `folder and try again.

**Comment by polymer-coder** [comment]
> > @chrisspiegl Yes, all done with environment variables. Check your deployment too…
> 
> @robokozo I'll respond to both things, starting with your first comment about your `nuxt.config.ts` file.
> 
> **nuxt.config.ts**
> 
> As you can see in [my demo repo about how I managed to get it to work](https://github.com/chrisspiegl/test-nuxt-vuefire-ssr/blob/c8e13a6c819d5ddc832077d8b8fe5ef4b135dc56/nuxt.config.ts#L14-L27), you do not need the admin account setup in the `nuxt.config.ts` file at all since those `.env` variables are actually used right inside the code from `vuefire` without the need to provide them inside the `nuxt.config.ts`. So your config should look like this:
> 
> ```js
> export default defineNuxtConfig({
>     modules: ["nuxt-vuefire"],
>     vuefire: {
>         auth: true,
>         config: {
>             apiKey: process.env.FIREBASE_API_KEY,
>             authDomain: process.env.FIREBASE_AUTH_DOMAIN,
>             projectId: process.env.FIREBASE_PROJECT_ID,
>             storageBucket: process.env.FIREBASE_STORAGE_BUCKET,
>             messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID,
>             appId: process.env.FIREBASE_APP_ID,
>         },
>     },
> })
> ```
> 
> By doing so, you should not see these API keys / the PRIVATE_KEY in the public js files.
> 
> **Deploy on Google Firebase:**
> 
> Yes, I deployed my test repo to both Firebase and Vercel (see [readme.md](https://github.com/chrisspiegl/test-nuxt-vuefire-ssr#firebase) on my test repo). Both worked and I was able to login and reload the page.
> 
> Also, with no real "special settings or setup". Aka: both used the same `nuxt.config.ts` setup and the only real difference is how the `.env` is deployed. Since the GCP Service Account will be provided by default in Google Firebase Functions, you do not need to provide those for the deploy at all.
> 
> Have a look into the `package.json` on my test repo to see how the build & deploy process for firebase worked for me.


This solved my issue but if you're still facing issues, after two days of trying, just delete your ` .nuxt` folder and try again.
