### ISSUE TITLE
Throws Firebase should be global

### ISSUE THREAD

**Issue by nueko** [vuejs/vuefire#134]
Just try to copy-paste the read me to vue webpack template throws
```
Uncaught Error: Firebase should be exposed as a global property
```

**Comment by posva** [comment]
It works well...
Please, ask on the [forum](http://forum.vuejs.org/) or the [Discord server](https://vue-land.js.org/) for this kind of questions. It's probably something simple, the kind of things you miss easily.
I tried with `import` instead of `require` and it works well with the webpack template
