### ISSUE TITLE
Example with database relations

### ISSUE THREAD

**Issue by bschmitt** [vuejs/vuefire#150]
I'm trying to find a way to combine database relations in a way that I can access them combined in the template. I'm using vue components.
All the examples with vuefire (and firebase) are very basic with only a single database table reference. I would be very happy if someone could target me to some docs or examples.

```
<template>
  <div>
    <pre>{{ data }}</pre>
  </div>
</template>

<script>
import firebase from 'firebase'

let config = {
  apiKey: '...',
  authDomain: ',,,',
  databaseURL: '...',
  projectId: '...',
  storageBucket: '...',
  messagingSenderId: '...'
}

let firebaseApp = firebase.initializeApp(config)

export default {

  data () {
    return {
      data: []
    }
  },

  // #1 is there a way to achieve that here?
  firebase: {
    table1: firebaseApp.database().ref('table1'),
    table2: firebaseApp.database().ref('table2')
  },

  // #2 tried the following but failed
  computed: {
    data: () => {
      let response = []

      firebaseApp.database().ref('table1').on('value', (snapshot) => {
        snapshot.forEach((childSnapshot) => {
          const key = childSnapshot.key

          // get relation
          firebaseApp.database().ref('table2/' + key).on('value', (relationSnapshot) => {
            response[key] = {
              ...childSnapshot.val(),
              table2: relationSnapshot.val()
            }
          })
        })
      })

      return response
    }
  }

}
</script>
```

**Comment by posva** [comment]
Hello, this is somehow intentional, we don't want to duplicate pieces of docs that belongs to Firebase on vuefire. This youtube videos can come in handy: https://www.youtube.com/watch?v=ran_Ylug7AE

From vuefire point of view, you need to generate refs that are bound to the final document. To achieve that, you can use watchers to unbind then bind references as they change. Those watchers can watch the original table or on another table that connects both tables (like in the video)
