### ISSUE TITLE
readyCallback equivalent in FireStore?

### ISSUE THREAD

**Issue by ShimShamSam** [vuejs/vuefire#157]
I don't see any replacement/documentation for readyCallback in the FireStore branch

**Comment by posva** [comment]
`$bind` now returns a promise 😃 so you get all the flexibility you can think of
There's no replacement (at least for the moment) when declaring it through firestore option, but in that case, `$bind` in the created or mounted event.

**Comment by posva** [comment]
g

**Comment by 185driver** [comment]
I see this issue is closed but I have the same question and I'm still pretty new to Vue/Firebase/Firestore. You mention that `$bind` now returns a promise, but what would the syntax look like if I'm returning an array and wish to determine when the data has finished loading? For instance, if:
```
var firebaseApp = firebase.initializeApp({ ... })
var db = firebaseApp.database()

var vm = new Vue({
  el: '#demo',
  firebase: {
    // I'm looking to return an array
    anArray: db.ref('url/to/my/collection'),

    // I know this next part is wrong, but it illustrates what I'm looking for
    readyCallback: function () {
      dataReady: true
    }
  }
})
```
How might I use `$bind` to determine when my Firestore data has loaded? Thank you.

**Comment by posva** [comment]
With the old firebase version, you will have to handle that manually as it uses callbacks, with the new firestorm you can just do `Promise.all` on an array containing the `$bind` calls

**Comment by 185driver** [comment]
@tiddler Thanks so much. That is indeed what I was searching for...a snippet to go by. It works perfectly.  My hope is that an example like this might make it into the Usage section of the Readme later since waiting for the Firestore data to be loaded before doing something seems like a common-enough thing.

**Comment by carlosaiello** [comment]
> @185driver This is my solution for your question.
> (*Please correct me if I am wrong) Currently, you can either implicitly bind the `firestoreRef` to your data by using the `firestore` declaration or use the `$bind` method by yourself, which will return you a `Promise`. Therefore, you can just do all things as usual, like `then()`, `catch()`.
> 
> ```js
> var firebaseApp = firebase.initializeApp({ ... })
> var db = firebaseApp.firestore()
> 
> var vm = new Vue({
>   el: '#demo',
>   data () {
>     return {
>       mydata: [],
>       dataReady: false
>     }
>   },
>   // Instead of using the 'firestore' declaration, manual binding is used
>   /*
>   firestore () {
>     return {
>       mydata: db.collection('some_col').doc('some_doc')
>     }
>   }
>   */
>   mounted () {
>     this.$bind('mydata', db.collection('some_col').doc('some_doc'))
>       .then((doc) => {
>         this.dataReady = true
>       })
>       .catch((error) => {
>         console.log('error in loading: ', error)
>       })
>   }
> })
> ```

what do you recommend in this case if you want to have a pagination?, since you are binding it when mounting.
I was thinking in doing it in a method (loadMore), if we are rebinding it everytime the page changes, then it will generate a blink of data (we will be reloading everything every time the pagination is executed and I think that's not a good idea)

another alternative i'm seeing is to rebind it to another variable every time the pagination is called, then pushing the items in a list using the then, but in that case we will loose the realtime changes (if someone is changing an item we will not see the changes)

what do you suggest in this case?

Thanks!

**Comment by ReneMoraales** [comment]
@posva I'm trying to use `$bind` to check whether data is loaded. Before, I've binded to the same collection, with a `limit` in the query, inside a different component. When I bind again in my second component, the promise resolves immediately with the limited results fetched before, instead of the new, "un-limited" results.

**Comment by posva** [comment]
Can you put that in a boiled down repro in a new issue so I ça take a look. I can't do much without a repro 😅
