### ISSUE TITLE
Issue With VueFire 3.2.0 and Firebase 11.0.1

### ISSUE THREAD

**Issue by lsecyber** [vuejs/vuefire#1581]
### Steps to reproduce the bug

1. Run `npm i firebase`
2. Run `npm i vuefire`
2. Check the output

### Expected behavior

It installs correctly with no errors.

### Actual behavior

This output is given:
```
npm i vuefire
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: vuefire@3.2.0
npm error Found: firebase@11.0.1
npm error node_modules/firebase
npm error   firebase@"^11.0.1" from the root project
npm error
npm error Could not resolve dependency:
npm error peerOptional firebase@"^9.0.0 || ^10.0.0" from vuefire@3.2.0
npm error node_modules/vuefire
npm error   vuefire@"*" from the root project
npm error
npm error Conflicting peer dependency: firebase@10.14.1
npm error node_modules/firebase
npm error   peerOptional firebase@"^9.0.0 || ^10.0.0" from vuefire@3.2.0
npm error   node_modules/vuefire
npm error     vuefire@"*" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error /Users/_{username_redacted}_/.npm/_logs/2024-10-23T20_12_00_862Z-eresolve-report.txt

npm error A complete log of this run can be found in: /Users/luke.ertzberger/.npm/_logs/2024-10-23T20_12_00_862Z-debug-0.log
```

### Additional information

It appears vuefire needs to be updated to support Firebase 11.0.1 and not only Firebase 9 or 10. Or the section in the docs stating "WARNING VueFire requires Firebase JS SDK >= 9 but is compatible with Vue 2 and Vue 3." should be updated to state that it requires the Firebase JS SDK 9 or 10 but doesn't support 11. If you run "npm i firebase vuefire" together it does install correctly, but that forces it to use firebase 10.14.1.

**Comment by sceee** [comment]
Adding to the above, I think the reason why the Firebase JS SDK v11 is a major release is due to the fact that it has breaking changes regarding the support for NodeJS:
Checking its [changelog](https://firebase.google.com/support/release-notes/js#version_1100_-_october_21_2024):
* "The SDK no longer supports versions of Node.js below version 18"
* "Removed ES5 bundles. The minimum required ES version is now ES2017."
* "Removed usage of undici and node-fetch dependencies in our Node.js bundles, replacing them with the native Node.js fetch implementation."

So according to the changelog it reads that there are no breaking changes that would break `vuefire` so I don't see a reason why the `peerDependencies` could not be extended to also support v11.

**Comment by pkorac** [comment]
Second all of the above.
```
npm install firebase
npx nuxi@latest module add vuefire
```

Currently fails as the new version of firebase isn't supported.

**Comment by nycynik** [comment]
How could I try to manually get around this? Is it possible to --force something to install? I would love to try it out and see if there are actually any breaking changes in 11, but I'm not sure how to do that. 

I tried:

    npm i vuefire --force

shows some warnings, but works. Then saw nuxt-vuefire@latest was a similar issue, so 

    npm install -D nuxt-vuefire@latest --force

Next I set up the configuration in the nuxt.config.ts file. I then see this config error, so - it's working

    [nuxt-vuefire module 4:11:34 PM]  WARN  You activated both SSR and auth but you are not providing a service account for the admin SDK. See https://vuefire.vuejs.org/nuxt/getting-started.html#configuring-the-admin-sdk.

I also have a 500 error to go along with that, but I suspect this is due to the error above. 

    The default Firebase app does not exist. Make sure you call initializeApp() before using any of the Firebase services.

So, I might try the same thing with a simple site, and not my actual project, and see how it goes. But it seems like with those two forces you can get it installed.

**Comment by MyNetCal** [comment]
Same here. I had to downgrade firebase to v.10.14.1. AWS didn't let me use vuefire 3.2 with Firebase v.11

**Comment by kn0wn** [comment]
In the meantime to suppress the warning using pnpm you can do;

```javascript
  "pnpm": {
    "packageExtensions": {
      "nuxt-vuefire@1.0.4": {
        "peerDependencies": {
          "firebase": "^9.0.0 || ^10.0.0 || ^11.0.0"
        }
      }
    },
    "peerDependencyRules": {
      "allowedVersions": {
        "firebase": "^9.0.0 || ^10.0.0 || ^11.0.0"
      }
    }
  }
```

**Comment by Tkkg1994** [comment]
@posva

We are truly eagerly waiting for an update of this module to keep it working with the latest version of firebase. You mentioned that you didn't get supported from nuxt nor google to do this.

If that's really the key issue, we can do a go fund me page. I'm sure more then most people here would donate something to keep you going!
