### ISSUE TITLE
$bindAsArray don't update binded data dynamically

### ISSUE THREAD

**Issue by monocles** [vuejs/vuefire#19]
#I'm trying to bind a child node dynamically after the event changes. 

```
...
var db = firebaseApp.database().ref('data/')

new Vue({
  el: '#app',
  data: {
    current: 'first',
    currentNode: []
  },
  firebase: {
    myArray: db
  },
  ready() {
  	this.$bindAsArray('currentNode', db.child(this.current))
  },
  watch: {
    'curent': function(node) {
      console.log(node)
      this.$bindAsArray('currentNode', db.child(this.current))
    }
  },
  methods: {
    pushToNode() {
        this.$firebaseRefs.currentNode.push({
          hello: 'hello',
          world: 'world'
        })
      }
  }
})
```
and I expect to receive data at the output on binded array  like this:
 ` <pre>{{ currentNode | json }}</pre>`

I have made 2 fiddle examples 
First with `$bindAsArray` which does not update the state after the event triggering. 
https://jsfiddle.net/tpq0x7zu/1/
 
And second one with `$bindAsObject` which updates the data after the child node changes. 
https://jsfiddle.net/f95a1zwx/5/

**Comment by monocles** [comment]
Ok. solve this with `vue.filter` 

```
Vue.filter('getCurrent', function (value, key) {
  let v = []
  value.filter(function(item) {
    if(item['.key'] === key) {
     v = item
    }
  })
  return v
})
```

**Comment by lunardog** [comment]
I'm having the same issue. Tried `this.$unbind` and bind again, but no good.

**Comment by lunardog** [comment]
I'm guessing it's a FeatureNotBug(TM), on Firebase level. You have a reference to `first`, got got all the add/remove/update events. If you bind to `second`, you get the events for `second`. If you bind to `first` again, firebase has no reason to inform you of the whole state again. 

 - You: "Hey Frank First, what's new?" 
 - First: "Here's a list of my children, aren't they cute?"
 - You: "Hey Steve Second, what's new?"
 - Second: "I have a new child!"
 - You: "Hey Frank First, what's new?"
 - First: "Nothing new since you asked me 5 seconds ago. `null` snapshot." => empty array in vuefire.

**Comment by lunardog** [comment]
Nope, the reason was on Vue side.

See PR:
https://github.com/vuejs/vuefire/pull/20/commits/5d5fe2a149211548f1af8f5805ca86f5a9761a2d

**Comment by mrcsmcln** [comment]
I am having a similar issue. The following code fails to display a JSON representation of `foo`:

```html
<div id="app">{{ foo | json }}</div>
```

```js
new Vue({
    el: '#app',
    ready() {
        this.$bindAsArray('groups', db.ref('foo').orderByChild('bar').equalTo('baz');
    }
})
```

Is this thought to be caused by the same error?
