### ISSUE TITLE
getting Error every time whenever i tried to use import firebase from vuefire

### ISSUE THREAD

**Issue by msatech** [vuejs/vuefire#237]
Could not find a declaration file for module 'vuefire'. 'c:/Users/MSAtech/Documents/vuejsfire/vuefirebaseexample/node_modules/vuefire/dist/vuefire.js' implicitly has an 'any' type.
  Try `npm install @types/vuefire` if it exists or add a new declaration (.d.ts) file containing `declare module 'vuefire';

**Comment by msatech** [comment]
Could not find a declaration file for module 'vuefire'. 'c:/Users/MSAtech/Documents/vuejsfire/vuefirebaseexample/node_modules/vuefire/dist/vuefire.js' implicitly has an 'any' type.
  Try `npm install @types/vuefire` if it exists or add a new declaration (.d.ts) file containing `declare module 'vuefire';

**Comment by posva** [comment]
Please provide more information when opening issues, what version are you on, what did you import. Types are included in `next` version. v1 do not include them, you will have to declare them yourself.
Closing because typings are already added for the RTDB in next version but it hasn't been released yet

**Comment by msatech** [comment]
vue version is vue 3
