### ISSUE TITLE
Question: LIF When binding a Firestore collection do we read all documents?

### ISSUE THREAD

**Issue by NoobTaco** [vuejs/vuefire#284]
I think I know but I need to be sure because the reads add up.

When I bind to the collection with vuexfire if I limit the number does it still read all my documents?

I am sorry if this is simple, I am trying to just ensure I am not the next person to write a blog post about a $30,000 firestore bill :)

My use case is that I have a DB that has over 300 documents in the main collection. I have had over 10K traffic already in the last week and that just adds up if I am reading in the whole collection. ANd I am cleaning up a poor design I made in the beginning when it would do multiple reads.

Any tips or information is GREATLY appreciated by this noob. In name and fear on this topic :)

**Comment by posva** [comment]
Unless you do pagination, yeah, it will read all the documents.
Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by NoobTaco** [comment]
Thank you for your answer. 

I am sorry for posting it here. But beside your reply, the forum, and Discord server is not listed anywhere.  Maybe add those to the documentation?

But thank you.
