### ISSUE TITLE
VueFire suddenly stopped loading data (no changes to my code)

### ISSUE THREAD

**Issue by drewstaylor** [vuejs/vuefire#290]
Hello, last week VueFire stopped loading data but I made zero changes to the source code. I hadn't worked on the project for over a month but the client called me in a panic. 

I can't seem to fix the issue or find out what causes it. A more detailed explanation of my issue can be viewed in this StackOverflow post: https://stackoverflow.com/questions/56531940/vue-js-app-with-firebase-realtime-database-and-vuefire-suddenly-stopped-working

The post is mine.

**Comment by posva** [comment]
If the code hasn't changed and it was working before the problem doesn't come from the code, as you can imagine. I did take a look but I don't see anything wrong there.
I'm closing this as it is a support question and I simply cannot provide that service

**Comment by drewstaylor** [comment]
@posva - The issue is that I have had to downgrade from 2.0.0 to 1.4.5 to make everything work as expected. This is a real issue for developers regarding Vuefire documentation and not something that should simply be dismissed and ignored, or worse: written off as "support". I can find nowhere in the documentation where it says the documentation provided does not work in any 2+ or 3+ release.

**Comment by posva** [comment]
So you did change the code: you upgraded to a major version. The documentation is for the latest version: v2
Regarding the migration, you can find them in the releases notes, which is what a developer should check when upgrading to a major because it implies breaking changes.
There was no documentation for v1, that's why there is no version notion on it.
It's sad you think I ignored you even though I answered the issue the very same day. Well now you know where to check if you want to migrate to v2: the changelog and releases notes

You are welcome

**Comment by drewstaylor** [comment]
@posva What changed was the version being distributed from unpkg.com. My source code did not change, but as the app is still a beta concept I didn't build the depencies locally. Nonetheless, when I encountered the issue I double checked and followed the documentation exactly, which you say is for v2 however it using the implementation for the v2 documentation does not work. To find the issue I basically downgraded from 2.x. This took hours.

**Comment by posva** [comment]
Some advice: always version your cdn links.
Your source code changes because you're importing a library and the new version was used, so the code of the application changes

You keep saying things don't work without giving any code sample or anything 🤷‍♂️

The code is tested and the documentation has already helped many people. Don't try to make it look like it's the documentation fault because it took you hours to figure out things

I'm not wasting more energy and time on an issue where the op is clearly not interested in helping the project.
However, other people had made contributions to docs by opening pr or by explicitly showing the code samples that were not clear, you are more than welcome to open issues and pr like that as I really appreciate that Karine bd of contributions!
