### ISSUE TITLE
[Bug Fix: Vuexfire] Promise resolving prematurely on collections

### ISSUE THREAD

**Issue by adamkpurdy** [vuejs/vuefire#426]
**Problem**: When binding to collections via the Vuexfire plugin the promise is resolving after the first item is written. 

**Expectation**: The promise should only be resolved after the last item in the collection is written to state.

Sample repo **This is a Quasar Project**: https://github.com/adamkpurdy/vuexfire_bug

After some research, it looks as if the first binding resolver from the [currentUser call](https://github.com/adamkpurdy/vuexfire_bug/blob/master/src/boot/firebase.js#L18) is triggering the promise resolver of the [second getUsers call](https://github.com/adamkpurdy/vuexfire_bug/blob/master/src/pages/Index.vue#L13).

The expectation is that the [console statement](https://github.com/adamkpurdy/vuexfire_bug/blob/master/src/pages/Index.vue#L15) should output a value of 3 for the length of the user's call from firestore. This not the case when the currentUser is called in the boot file, as the output is 1. If the call to the currentUser is commented out, the output in the console will be 3 as expected.

*A Firebase project has been set up for this repo, and initialized.*

Any guidance or direction would be appreciated.

Thank you.

**Comment by posva** [comment]
Could you put this on a boiled down repro please? with only firebase, vue, vuex and vuexfire?

**Comment by adamkpurdy** [comment]
Upon boiling down the repo outside of the Quasar framework, the bug was not reproducible.

**Comment by anubhavkamath** [comment]
I know this issue is closed and it's over a year later but I'm having the exact same problem. What is the solution to this? Not use quasar? I don't know how quasar would be the issue.

**Comment by adamkpurdy** [comment]
@anubhavkamath I believe how I restructured my Quasar application code solved this. Due to the time and looking into the context of this example I can not remember specifics on where this was a problem with old UX. This is example was a boiled-down version of a project I was working on. Feel free to reach out to me on Quasar's Discord server(@Adam P) if you have specific questions about your UX and integrating Firebase & Quasar.

**Comment by anubhavkamath** [comment]
Thanks. I tried messaging you on discord. but it says you have to add me as a friend. I sent a message directed to you on the introductions channel though. My handle is Anubhav.
Anu
    On Friday, January 22, 2021, 09:02:32 AM CST, Adam Purdy <notifications@github.com> wrote:  
 
 


@anubhavkamath I believe how I restructured my Quasar application code solved this. Due to the time and looking into the context of this example I can not remember specifics on where this was a problem with old UX. This is example was a boiled-down version of a project I was working on. Feel free to reach out to me on Quasar's Discord server(@adam P) if you have specific questions about your UX and integrating Firebase & Quasar.
