### ISSUE TITLE
Firebase ref in tests doesn't have the rights

### ISSUE THREAD

**Issue by posva** [vuejs/vuefire#44]
Right now tests are failing because we use a ref we don't have the rights to access anymore `oss-test.firebaseapp.com`.
@jwngr Do you have any advice about what to use for tests? I found incomplete, unofficial mocks and a Firebase server that seemed to be have many caveats making it hard to use for tests.

**Comment by jwngr** [comment]
Sorry, that's my fault. I changed the rules temporarily yesterday to test something and I never switched it back to publicly readable and writable. Should be fixed now. You could use your own Firebase project instead of the one we use for our other open source projects or I could just stop messing with that database :) We don't have an official mock at the moment. Unfortunately, it's a non-trivial project.

**Comment by posva** [comment]
Thanks @jwngr 🙂 
Well, it's yours after all, you can do whatever you want with it. About testing I also found this: https://github.com/urish/firebase-server but having to change etc/hosts doesn't look right to me 😕 
I could build a specific mock for vuefire since we're not using that much features but I don't think it's yet necessary
