### ISSUE TITLE
vuefire declaritive two way binding

### ISSUE THREAD

**Issue by BentleyDavis** [vuejs/vuefire#60]
This is excellent code.

I plan on using this in the future and I am hoping to not have to simplify the use.

Before I start, I wanted to make sure that it really isn't there or that I am not understanding a technical limitation or philosophy of Vue. In the todo example https://jsfiddle.net/posva/wtyop5jy/ it would be nice if instead of
`<input :value="todo.text" @input="updateTodoText(todo, $event.target.value)">` we could do  `<input v-model="todo.text" ">` and the changes would be persisted back to the Firebase database. Is this impossible or just difficult?

Thank you,
Bentley

**Comment by posva** [comment]
Glad you find it useful 🙂 

You can use a setter in a computed property to get that sugar syntax but it's not something that will be implemented in vuefire, at least in the near future, because they're a lot of edge cases and they're a lot of cases when you need to update multiple entities at the same time, therefore using the Firebase API instead. Overall, it's not worth adding because it won't be able to handle multiple pathes updates and other Firebase specific features that are related to how Firebase works

**Comment by BentleyDavis** [comment]
(No need for reply) I think I understand your reasoning. I was going to use this as a rapid prototyping tool. Moving the burdon from the HTML to JavaScript provides no value. Handling multiple paths would be something I expect it to provide to some extent. In either case, since it is an optional feature, edge cases do not reduce the value it provides for the simple cases it could be used for. The down side is of course explaining those edge cases to each new dev that tries to use it. If you have a moment to specify some of the edge cases I can try and address them.

**Comment by posva** [comment]
To put it in a nutshell, I don't want to add an incomplete and/or buggy feature that adds complexity to the project. I'll rather keep it simple and use what already exists to handle that complexity: the firebase API. You need it anyways, so better use what exists instead of replicating a similar behaviour on vuefire.
I find it more intuitive to use Firebase everywhere that use it for some specific modifications of the database

**Comment by BentleyDavis** [comment]
My impression is that declaritive two way binding is a core feature of Vue and without it vuefire is incomplete. I have not yet seen a technical reason it would have to be buggy or complex. If you don't have the time to share specifics then I'm sure I'll run into it before long.

**Comment by brockpetrie** [comment]
@BentleyDavis Have you explored this further? One of the most useful parts of AngularFire's implementation is their 3-way data binding, and it just feels like this library falls a bit short without it. If I'm manually writing all of my setters, and I'm manually interacting with the Firebase API for everything but the most basic queries, a great deal of potential utility here is lost. No offense meant to the author.

**Comment by franciscolourenco** [comment]
Was this issue closed accidentally by https://github.com/vuejs/vuefire/commit/65f1941f9e2059c7e2ddf7e89af2682924df4be6 ?

**Comment by franciscolourenco** [comment]
3-way data sync is the expected behaviour. This limitation should be added to the README. It is not intuitive that after modifying the model with `v-model`, firebase and the model become out of sync.
