### ISSUE TITLE
How to sort?

### ISSUE THREAD

**Issue by lukeramsden** [vuejs/vuefire#78]
I would I sort a firebase binding for the database? I have a createdOn value for every object, and I'd like to sort from newest to oldest, but its currently the otherway round. I tried using Lodash, like this:
```
  firebase: {
    surveys: _.reverse(surveys),
  },
```

But it didn't work.

**Comment by posva** [comment]
By using an orderBy method: https://firebase.google.com/docs/reference/js/firebase.database.Query#orderByChild

You could have at least googled that 😜

**Comment by lukeramsden** [comment]
@posva Sorry I'm quite new to Vue and lodash :P

**Comment by lukeramsden** [comment]
Oh I didn't realize Firebase had any helpers build in, thanks!

**Comment by lukeramsden** [comment]
@posva How do I reverse it? I want it in descending order, not ascending order, but I can't find anything in the Firebase docs for it

**Comment by posva** [comment]
You can't do it with firebase, you'll have to use a computed property. Please post further questions on the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks!

**Comment by Yatima-Kagurazaka** [comment]
@posva 
I can reverse fetched db data to do it.
But new writed data is inserted to unexpected position... 😞

**Comment by posva** [comment]
It looks like you can actually do it: https://groups.google.com/forum/#!msg/firebase-talk/5XSirxJnOMY/nLaOMwiHMskJ

**Comment by Yatima-Kagurazaka** [comment]
Thanks for your leading 😄

**Comment by chrisspiegl** [comment]
I found this issue and could not really decipher a solution:

1. I am sorting the collection I am requesting by using `query` and `orderBy` from firebase.
2. It displays the collection sorted by my requested arguments.
3. I change the data in a sub view
4. the data is updated in place but the sort order does not change despite the `orderBy` target field being changed?

Is there a way to have the collection be reordered?
Am I missing something?
Should I manually sort the collection in my view? (if so, how does one do that? Since just calling `articles.sort()` does not seem to work, I also tried `articles.values.sort()` but I think I probably shouldn't go that deep into it?
